name: Release Minor

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  dotnet-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: gonatienza/_python4cpm
          token: ${{ secrets._PYTHON4CPM_TOKEN }}
          path: _python4cpm
      - name: Get private repo files
        run: |
          Expand-Archive -Path "_python4cpm\Credentials Management .NET SDK*.zip" -DestinationPath "_python4cpm\framework"
          New-Item -ItemType Directory -Force -Path "src\plugin\lib"
          Copy-Item -Path "_python4cpm\framework\CyberArk.Extensions.Utilties.dll" -Destination "src\plugin\lib"
          Copy-Item -Path "_python4cpm\framework\CyberArk.Extensions.Plugins.Models.dll" -Destination "src\plugin\lib"
      - uses: microsoft/setup-msbuild@v2
      - name: Build .NET Release
        run: |
          msbuild src\plugin\Python4CPM.csproj /p:Configuration=Release /p:Platform="AnyCPU"
      - name: Zip platform
        run: |
          New-Item -ItemType Directory -Force -Path "dist\platform"
          Copy-Item -Path "src\plugin\bin\Release\CyberArk.Extensions.Plugin.Python4CPM.dll" "dist\platform"
          Copy-Item -Path "src\plugin\platform\*" "dist\platform"
          Compress-Archive -Path dist\platform\* -DestinationPath dist\python4cpm-platform.zip -Force
      - uses: actions/upload-artifact@v4
        with:
          name: platform-artifact
          path: dist/python4cpm-platform.zip
  
  update-release:
    needs: [dotnet-build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extract version
        run: |
          MAJOR_VERSION=$(python -c "import tomllib; print(tomllib.load(open('pyproject.toml','rb'))['project']['version'])")
          echo "MAJOR_VERSION=$MAJOR_VERSION" >> $GITHUB_ENV
          MINOR_VERSION=$(grep 'AssemblyFileVersion' src/plugin/Properties/AssemblyInfo.cs | sed -E 's/.*"([^"]+)".*/\1/')
          echo "MINOR_VERSION=$MINOR_VERSION" >> $GITHUB_ENV
      - uses: actions/download-artifact@v4
        with:
          name: platform-artifact
          path: dist
      - name: Add minor
        run: |
          mv dist/python4cpm-platform.zip dist/python4cpm-platform-${MINOR_VERSION}.zip
          gh release upload v${MAJOR_VERSION} \
            dist/python4cpm-platform-${MINOR_VERSION}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
